-- Import all 38 listings from CSV
-- Just copy and paste this into Supabase SQL Editor

INSERT INTO public.listings (title, category, location, rating, price_range, images, affiliate_link, featured, created_at) VALUES
('Muri Lagoon BBQ Lunch Cruise with Snorkeling', 'experience', 'Rarotonga, Cook Islands', 4.8, 'per person', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/2f/18/8d/9b/caption.jpg?w=1400&h=1000&s=1'], 'https://www.viator.com/tours/Rarotonga/Half-Day-Muri-Lagoon-BBQ-Lunch-Cruise-including-Snorkeling/d22128-9214P1', false, NOW()),
('Ruby Bea Hotel', 'hotel', 'Florence, Italy', 4.7, 'per night', ARRAY['https://images.trvl-media.com/lodging/103000000/102430000/102429800/102429735/709afed8.jpg?impolicy=resizecrop&rw=1200&ra=fit'], 'https://tinyurl.com/4v4hvrwp', false, NOW()),
('Secret Food Tours', 'experience', 'Paris, France', 4.9, 'per person', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/2e/a7/93/45/caption.jpg?w=1400&h=1000&s=1'], 'https://www.viator.com/tours/Paris/Secret-Food-Tours-Paris/d479-7812P1', false, NOW()),
('Casa Camper', 'hotel', 'Barcelona, Spain', 4.5, 'per night', ARRAY['https://images.trvl-media.com/lodging/2000000/1180000/1177400/1177369/20b89f97.jpg?impolicy=resizecrop&rw=1200&ra=fit'], 'https://tinyurl.com/2v2j7vc4', false, NOW()),
('Versailles Tour', 'experience', 'Paris, France', 4.9, 'per person', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/30/6a/f3/40/caption.jpg?w=1400&h=1000&s=1'], 'https://www.viator.com/tours/Versailles/Golden-Versailles-Palace-and-Garden-Tour/d763-67584P2', false, NOW()),
('InterContinental ANA', 'hotel', 'Tokyo, Japan', 4.7, 'per night', ARRAY['https://images.trvl-media.com/lodging/1000000/30000/22200/22199/eb48e1f5.jpg?impolicy=resizecrop&rw=1200&ra=fit'], 'https://tinyurl.com/2n3c7hm7', false, NOW()),
('Tuscan Cooking Class', 'experience', 'San Gimignano, Italy', 4.8, 'per person', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/2f/31/a0/ec/caption.jpg?w=1400&h=1000&s=1'], 'https://www.viator.com/tours/San-Gimignano/Tuscan-cooking-class/d29096-242735P2', false, NOW()),
('The Social Hub Belfiore', 'hotel', 'Florence, Italy', 4.5, 'per night', ARRAY['https://images.trvl-media.com/lodging/111000000/110560000/110551000/110550930/66ceba72.jpg?impolicy=resizecrop&rw=1200&ra=fit'], 'https://tinyurl.com/24d62c35', false, NOW()),
('3 Course Seine River Dinner Cruise', 'experience', 'Paris, France', 4.6, 'per person', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/2e/a7/89/37/caption.jpg?w=1400&h=1000&s=1'], 'https://www.viator.com/tours/Paris/Bistro-Style-Seine-River-Dinner-Cruise/d479-6557DINNERCRUISE', false, NOW()),
('Konzelmann Winery Ice Wine Tasting', 'experience', 'Niagara, Canada', 4.6, 'per person', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/16/74/68/ab/exterior-of-konzelmann.jpg?w=800&h=-1&s=1'], 'https://www.viator.com/tours/Niagara-Falls-and-Around/Konzelmann-Estate-Winery-Ice-Wine-Tasting/d687-5449ICEWINE', false, NOW()),
('Casa Camilla Hotel', 'hotel', 'Padova, Italy', 4.5, 'per night', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/1b/35/7e/af/the-best-history-experts.jpg?w=1100&h=-1&s=1'], 'https://tinyurl.com/tagalongacasa', false, NOW()),
('Six Senses Ibiza', 'hotel', 'Ibiza, Spain', 4.6, 'per night', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/1d/3d/7f/11/sea-scape-one-bedroom.jpg?w=1400&h=-1&s=1'], 'https://tinyurl.com/tagalongibiza', true, NOW()),
('Hoshinoya Karuizawa', 'hotel', 'Nagano, Japan', 4.7, 'per night', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/12/1b/b4/d6/hoshinoya-karuizawa.jpg?w=2000&h=-1&s=1'], 'https://tinyurl.com/tagalongjapan', true, NOW()),
('Conrad Maldives', 'hotel', 'Rangali Island, Maldives', 4.9, 'per night', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/10/8f/31/a9/main-island.jpg?w=2000&h=-1&s=1'], 'https://tinyurl.com/tagalongmaldives', true, NOW()),
('Belmond Hotel Caruso', 'hotel', 'Amalfi Coast, Italy', 4.8, 'per night', ARRAY['https://dynamic-media.tacdn.com/media/photo-o/16/de/c9/de/belmond-hotel-caruso.jpg?w=1400&h=-1&s=1'], 'https://tinyurl.com/tagalongamalfi', true, NOW()),
('Tokyo Record Bar', 'restaurant', 'New York City, USA', 4.7, 'per person', ARRAY['https://i.imgur.com/S2OxiuH.png'], 'https://tinyurl.com/tagalongtokyo', false, NOW()),
('La Cuisine Paris Cooking Class', 'experience', 'Paris, France', 4.8, 'per person', ARRAY['https://i.imgur.com/bp73DTL.png'], 'https://lacuisineparis.com/paris-cooking-classes', false, NOW());